accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from .views import LoginView

app_name = 'accounts'
urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login')),
    path('login', LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

highschool/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views

app_name = 'highschool'
urlpatterns = [
    # example: /lycee/
    path('', views.index, name='index'),

    # Example (see all): /lycee/students
    path('students', views.StudentListView.as_view(), name='student-list'),
    # Example (see specific): /lycee/student/1
    path('student/<int:pk>', views.StudentDetailView.as_view(), name='student-detail'),
    # Example (create): /lycee/student/create
    path('student/create', views.StudentCreateView.as_view(), name='student-create'),
    # Example (edit): /lycee/student/edit/1
    path('student/update/<pk>', views.StudentUpdateView.as_view(), name='student-update'),
    # Example (delete): /lycee/student/delete/1
    path('student/delete/<pk>', views.StudentDeleteView.as_view(), name='student-delete'),

    #region -> (permissions)

    path('groups', views.GroupListView.as_view(), name='group-list'),
    path('group/<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('group/create', views.GroupCreateView.as_view(), name='group-create'),
    path('group/update/<int:pk>', views.GroupUpdateView.as_view(), name='group-update'),
    path('group/delete/<int:pk>', views.GroupDeleteView.as_view(), name='group-delete'),

    # endregion

    # region -> (teachers)

    path('teachers', views.TeacherListView.as_view(), name='teacher-list'),
    path('teacher/<int:pk>', views.TeacherDetailView.as_view(), name='teacher-detail'),
    path('teacher/create', views.TeacherCreateView.as_view(), name='teacher-create'),
    path('teacher/update/<int:pk>', views.TeacherUpdateView.as_view(), name='teacher-update'),
    path('teacher/delete/<int:pk>', views.TeacherDeleteView.as_view(), name='teacher-delete'),

    # endregion

    # region -> (academic grades)

    path('academic-grades', views.AcademicGradeListView.as_view(), name='academic-grade-list'),
    path('<int:pk>', views.AcademicGradeDetailView.as_view(), name='academic-grade-detail'),
    path('academic-grade/create', views.AcademicGradeCreateView.as_view(), name='academic-grade-create'),
    path('academic-grade/update/<int:pk>', views.AcademicGradeUpdateView.as_view(), name='academic-grade-update'),
    path('academic-grade/delete/<int:pk>', views.AcademicGradeDeleteView.as_view(), name='academic-grade-delete'),

    # endregion

    # region -> (classroom)

    path('classrooms', views.ClassroomListView.as_view(), name='classroom-list'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/create', views.ClassroomCreateView.as_view(), name='classroom-create'),
    path('classroom/update/<int:pk>', views.ClassroomUpdateView.as_view(), name='classroom-update'),
    path('classroom/delete/<int:pk>', views.ClassroomDeleteView.as_view(), name='classroom-delete'),

    # Classroom calls registers
    # path('classroom/<int:pk>/call_registers', views.ClassroomAttendanceListView.as_view(), name='classroom-call-register-list'),
    # path('classroom/<int:class_id>/call_register/<int:pk>', views.ClassroomAttendanceCreateView.as_view(), name='classroom-call-register-detail'),
    # path('classroom/<int:pk>/call_register/create', views.ClassroomAttendanceCreateView.as_view(), name='classroom_call_the_roll'),
    # path('classroom/<int:class_id>/call_register/update/<int:pk>', views.ClassroomAttendanceCreateView.as_view(), name='classroom-call-register-update'),
    # path('classroom/<int:class_id>/call_register/delete/<int:pk>', views.ClassroomAttendanceCreateView.as_view(), name='classroom-call-register-delete'),

    # Classroom planning
    path('classroom/<int:class_id>/planning', views.ClassroomPlanning.as_view(), name='classroom-planning'),

    # Classroom lessons management
    path('classroom/<int:class_id>/lessons', views.ClassroomLessonListView.as_view(), name='classroom-lesson-list'),
    path('classroom/<int:class_id>/lesson/<int:pk>', views.ClassroomLessonDetailView.as_view(), name='classroom-lesson-detail'),
    path('classroom/<int:class_id>/lesson/create', views.ClassroomLessonCreateView.as_view(), name='classroom-lesson-create'),
    path('classroom/<int:class_id>/lesson/update/<int:pk>', views.ClassroomLessonUpdateView.as_view(), name='classroom-lesson-update'),
    path('classroom/<int:class_id>/lesson/delete/<int:pk>', views.ClassroomLessonDeleteView.as_view(), name='classroom-lesson-delete'),

    # Classroom lesson attendance
    path('classroom/<int:class_id>/lesson/<int:lesson_id>/call_register/create', views.LessonAttendanceCreateView.as_view(), name='classroom-lesson-attendance-create'),
    path('classroom/<int:class_id>/lesson/<int:lesson_id>/call_register/update', views.LessonAttendanceUpdateView.as_view(), name='classroom-lesson-attendance-update'),


    # path('classroom/<int:class_id>/course/create', name='classroom-course-create'),

    # endregion

    # region -> (subject)

    path('subjects', views.SubjectListView.as_view(), name='subject-list'),
    path('subject/<int:pk>', views.SubjectDetailView.as_view(), name='subject-detail'),
    path('subject/create', views.SubjectCreateView.as_view(), name='subject-create'),
    path('subject/update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject-update'),
    path('subject/delete/<int:pk>', views.SubjectDeleteView.as_view(), name='subject-delete'),

    # endregion
]

schoolmanagementapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

handler400 = 'highschool.views.handler400'
handler403 = 'highschool.views.handler403'
handler404 = 'highschool.views.handler404'
# handler500 = 'highschool.views.handler500'


urlpatterns = [
    path('', RedirectView.as_view(url="/lycee/")),
    path('', include('accounts.urls')),
    path('lycee/', include('highschool.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('accounts.urls'))
]

highschool/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.core.exceptions import ValidationError

import sys

class SexGenre(models.IntegerChoices):
    UNKNOWN = 0
    MALE = 1
    FEMALE = 2

class Subject(models.Model):
    """ This model is used to represent a specific subject. """

    # Non-relational model fields
    name = models.CharField(max_length=255)
    color = models.CharField(
        validators=[RegexValidator(
            regex=r'^#(?:[0-9a-fA-F]{1,2}){3}$',
            message='La couleur doit être écrite au format hexadécimal'
        )],
        max_length=7,
        null=False,
        default='#4287f5'
    )

    def __str__(self):
        return "%s" % self.name

class CourseHour(models.Model):
    """ This model is used to represent a specific course at a specific hour. """

    # Relational model fields
    classroom_subject = models.ForeignKey('ClassroomTeacher', on_delete=models.SET_NULL, null=True)

    # Non-relational model fields
    start_at = models.DateTimeField(default=timezone.datetime.today)
    end_at = models.DateTimeField(default=timezone.datetime.today)

class AcademicGrade(models.Model):
    """ This model is used to represent the academic grade. """

    # Non-relational model fields
    diploma_short_name = models.CharField(max_length=35)
    diploma_full_name = models.CharField(max_length=255)
    formation_short_name = models.CharField(max_length=255)
    formation_full_name = models.CharField(max_length=255)
    year_after_bac = models.IntegerField(help_text='Spécifiez le nombre d\'années avant ou après le BAC concernant le diplôme')

    def __str__(self):
        return "%s %s (BAC+%s)" % (self.diploma_short_name, self.formation_short_name, self.year_after_bac)

    def short_name(self):
        return "%s %s" % (self.diploma_short_name, self.formation_short_name)

    def long_name(self):
        return "%s %s" % (self.diploma_full_name, self.formation_full_name)


class Teacher(models.Model):
    """ This model represents a school teacher."""

    # Relational model fields
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    subject = models.ForeignKey('Subject', on_delete=models.SET_NULL, null=True, blank=True)

    # Non-relational model fields
    genre = models.IntegerField(choices=SexGenre.choices, default=SexGenre.UNKNOWN)
    birth_date = models.DateField(default=timezone.datetime.today)
    phone = models.CharField(
        validators=[RegexValidator(
            regex=r'^\+33[1-9][0-9]{8}$',
            message='Le numéro de téléphone doit suivre le format "+33125460945".'
        )],
        max_length=12,
        null=False,
        default='+33645712082'
    )

    def __str__(self):
        return "%s %s (%s)" % (
            self.user.first_name,
            self.user.last_name,
            self.subject.name if self.subject is not None else 'Aucun'
        )

    def full_name(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def delete(self, using=None, keep_parents=False):
        self.user.delete()
        return super(Teacher, self).delete(using, keep_parents)


class ClassroomTeacher(models.Model):
    """ This model represents the ManyToMany relationship between Classroom and Teacher. """

    # Relational model fields
    teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE, null=True)
    classroom = models.ForeignKey('Classroom', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "%s / %s" % (self.teacher, self.classroom)

    def teacher_name(self):
        return self.teacher.full_name()

    def subject_name(self):
        return self.teacher.subject.name

    def course_name(self):
        return "%s" % self.teacher


class Classroom(models.Model):
    """ This model represents the classroom at a specific year. """

    # Relational model fields
    academic_grade = models.ForeignKey(AcademicGrade, on_delete=models.SET_NULL, null=True)
    teachers = models.ManyToManyField('Teacher', through='ClassroomTeacher')
    students = models.ManyToManyField('Student')

    # Non-relational model fields
    start_at = models.DateTimeField(default=timezone.datetime.today)
    end_at = models.DateTimeField(default=timezone.datetime.today)
    class_name = models.CharField(max_length=150, default="class_name")

    def __str__(self):
        return "%s (%s - %s)" % (self.class_name, self.start_at.year, self.end_at.year)

    def lessons(self):
        return [lesson for class_teacher in list(self.classroomteacher_set.all()) for lesson in list(class_teacher.lesson_set.all())]


class Attendance(models.Model):

    # Relational model fields
    lesson = models.ForeignKey('Lesson', on_delete=models.CASCADE, null=True)
    student = models.ForeignKey('Student', on_delete=models.CASCADE, null=True)

    # Non-relational model fields
    is_absent = models.BooleanField(default=False)

    def __str__(self):
        return "Appel du %s pour %s au cours %s" % (
            self.lesson.start_at.strftime('%d/%m/%Y à %H:%M:%S'),
            self.student,
            self.lesson.simple()
        )


class Student(models.Model):
    """ Students within the SMA are represented by this model. """

    # Relational model fields
    user = models.OneToOneField(to=User, on_delete=models.SET_NULL, null=True)

    # Non-relational model fields
    genre = models.IntegerField(choices=SexGenre.choices, default=SexGenre.UNKNOWN)
    birth_date = models.DateField(default=timezone.datetime.utcnow)
    phone = models.CharField(
        validators=[RegexValidator(
            regex=r'^\+33[1-9][0-9]{8}$',
            message='Le numéro de téléphone doit suivre le format "+33125460945".'
        )],
        max_length=12,
        null=False,
        default='+33645712082'
    )

    def __str__(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def delete(self, using=None, keep_parents=False):
        self.user.delete()
        super(Student, self).delete(using, keep_parents)

    def absences(self):
        return self.attendance_set.filter(is_absent=True)


class Grade(models.Model):
    """ This model represents the grade for a specific student. """

    # Relational model fields
    student = models.ForeignKey('Student', on_delete=models.CASCADE, null=True)
    course = models.ForeignKey('ClassroomTeacher', on_delete=models.CASCADE, null=True)

    # Non-relational model fields
    grade = models.IntegerField(
        validators=[
            MaxValueValidator(20),
            MinValueValidator(0)
        ]
    )
    coefficient = models.FloatField(
        validators=[
            MinValueValidator(0)
        ]
    )


class Lesson(models.Model):
    """ This model represents the lesson itself. """

    # Relational model fields
    classroom_teacher = models.ForeignKey(ClassroomTeacher, on_delete=models.CASCADE, null=True)

    # Non-relational model fields
    start_at = models.DateTimeField(default=timezone.datetime.today)
    end_at = models.DateTimeField(default=timezone.datetime.today)

    def __str__(self):
        return "%s avec %s pour la classe %s" % (
            self.classroom_teacher.teacher.subject,
            self.classroom_teacher.teacher.full_name(),
            self.classroom_teacher.classroom.class_name
        )

    def has_attendance(self):
        return self.attendance_set.count() > 0

    def absent_students(self):
        return [attendance.student for attendance in list(self.attendance_set.filter(is_absent=True))]

    def simple(self):
        return "Leçon n° %d, le %s de %s à %s" %(
            self.id,
            self.start_at.strftime('%d/%m/%Y'),
            self.start_at.strftime('%H:%M'),
            self.end_at.strftime('%H:%M')
        )

    def page_title(self):
        return "Leçon de &laquo; %s &raquo; du %s à %s" % (
            self.subject().name,
            self.start_at.strftime('%d/%m/%Y'),
            self.start_at.strftime('%H:%M'),
        )

    def teacher(self):
        return self.classroom_teacher.teacher

    def subject(self):
        return self.classroom_teacher.teacher.subject

    def subject_name(self):
        return self.subject().name

    def subject_color(self):
        return self.subject().color

highschool/forms/academic_grade.py
from django import forms

from ..models import AcademicGrade


class AcademicGradeForm(forms.ModelForm):
    class Meta:
        model = AcademicGrade
        fields = ['diploma_short_name', 'diploma_full_name', 'formation_short_name', 'formation_full_name', 'year_after_bac']

highschool/views/academic_grade.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from ..models import AcademicGrade
from ..forms import AcademicGradeForm


class AcademicGradeListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    """ Lists all existing academic grades. """
    paginate_by = 25
    ordering = ['-id']
    model = AcademicGrade
    template_name = 'highschool/academic-grade/list.html'

    permission_required = (
        'highschool.view_academicgrade'
    )


class AcademicGradeDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    """ Details a specific academic grade. """
    model = AcademicGrade
    template_name = 'highschool/academic-grade/detail.html'

    permission_required = (
        'highschool.view_academicgrade'
    )


class AcademicGradeCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    """ Creates a new academic grade. """
    form_class = AcademicGradeForm
    success_url = reverse_lazy('highschool:academic-grade-list')
    template_name = 'highschool/academic-grade/create.html'

    permission_required = (
        'highschool.create_academicgrade'
    )

    def get_context_data(self, **kwargs):
        print(self.request.user.get_all_permissions())
        context = super(AcademicGradeCreateView, self).get_context_data(**kwargs)
        context['cs_form_type'] = 'create'
        return context


class AcademicGradeUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    """ Updates a specific academic grade. """
    model = AcademicGrade
    form_class = AcademicGradeForm
    template_name = 'highschool/academic-grade/update.html'

    permission_required = (
        'highschool.change_academicgrade'
    )

    def get_context_data(self, **kwargs):
        context = super(AcademicGradeUpdateView, self).get_context_data(**kwargs)
        context['cs_form_type'] = 'update'
        return context

    def get_success_url(self):
        return reverse_lazy('highschool:academic-grade-detail', args=[self.object.id])


class AcademicGradeDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    """ Deletes a specific academic grade. """
    model = AcademicGrade
    template_name = 'highschool/academic-grade/delete.html'
    success_url = reverse_lazy('highschool:academic-grade-list')

    permission_required = (
        'highschool.delete_academicgrade'
    )

highschool/templates/highschool/classroom/create.html
{% extends 'highschool/classroom/form.html' %}

{{% block title %}Création d'une classe{% endblock %}

highschool/templates/highschool/classroom/delete.html
{% extends 'base.html' %}

{% block title %}Suppression de la classe &laquo; {{ classroom.class_name }} &raquo;{% endblock %}

{% block content %}
    <div class="row">
        <div class="column">
            <h1 class="ui header dividing">
                <div class="content">
                    Suppression de la classe &laquo; {{ classroom.class_name }} &raquo;
                    <div class="sub header">Supprimer une classe et ses dépendances</div>
                </div>
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="column">
            <div class="ui icon warning message">
                <i class="exclamation triangle icon"></i>
                <div class="content">
                    <div class="header">
                        Vous allez supprimer une classe, la suppression de cette classe implique :
                    </div>
                    <div class="ui list">
                        <div class="item">
                            <i class="check green icon"></i>
                            <div class="content">
                                La suppression <b>définitive et irréversible</b> de la classe
                            </div>
                        </div>
                        <div class="item">
                            <i class="check green icon"></i>
                            <div class="content">
                                La suppression <b>de l'historique de la classe (élèves, notes, etc.)</b>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="column">
            <form method="post" class="ui form right aligned basic segment">
                {% csrf_token %}
                <div class="ui buttons">
                    <a href="{% url 'highschool:classroom-detail' classroom.id %}" class="ui button">Annuler</a>
                    <div class="or" data-text="ou"></div>
                    <input type="submit" value="Confirmer" class="ui negative button">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

highschool/templates/highschool/classroom/detail.html
{% extends 'base.html' %}

{% block title %}Classe &laquo; {{ classroom }} &raquo;{% endblock %}


{% block content %}
    {# Page title #}
    <div class="sixteen wide column">
        <h2 class="ui icon header d-block">
            <i class="users icon"></i>
            <div class="content">
                Classe &laquo; {{ classroom }} &raquo;
                <div class="sub header">Visualiser et gérer une classe spécifique.</div>
            </div>
        </h2>
    </div>

    <div class="sixteen wide column">
        <h3 class="ui header dividing">Informations</h3>
    </div>

    {# Actions #}
    <div class="eight wide computer sixteen wide mobile column">
        <a href="{% url 'highschool:classroom-update' classroom.id %}" class="ui labeled icon button d-block">
            <i class="edit icon"></i>
            Mettre à jour
        </a>
    </div>
    <div class="eight wide computer sixteen wide mobile column">
        <a href="{% url 'highschool:classroom-delete' classroom.id %}" class="ui labeled icon negative button d-block">
            <i class="trash icon"></i>
            Supprimer
        </a>
    </div>

    {# Classroom informations #}
    <div class="sixteen wide column">
        <div class="ui middle aligned relaxed list">
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Nom de la classe : </b>{{ classroom.class_name }}
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Formation : </b>{{ classroom.academic_grade }}
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Dates de la classe : </b>{{ classroom.start_at|date:"Y" }} - {{ classroom.end_at|date:"Y" }}
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Nombre d'étudiant(s) : </b>{{ classroom.students.count }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="sixteen wide column">
        <h3 class="ui header dividing">Liste des professeurs & matières</h3>
    </div>

    {# Actions #}
    <div class="eight wide computer sixteen wide mobile column">
        <a href="{% url 'highschool:classroom-planning' class_id=classroom.id %}" class="ui labeled icon button blue d-block {% if classroom.teachers.count <= 0 %}disabled{% endif %}">
            <i class="calendar alternate outline icon"></i>
            Voir l'emploi du temps
        </a>
    </div>
    <div class="eight wide computer sixteen wide mobile column">
        <a href="{% url 'highschool:classroom-lesson-list' class_id=classroom.id %}" class="ui labeled icon button blue d-block {% if classroom.teachers.count <= 0 %}disabled{% endif %}">
            <i class="calendar alternate outline icon"></i>
            Gestion des cours
        </a>
    </div>

    <div class="sixteen wide column">
        {% if classroom.teachers.count > 0 %}
            <div class="ui middle aligned relaxed list">
                {% for teacher in classroom.teachers.all %}
                    <div class="item">
                        <i class="angle right icon"></i>
                        <div class="content">
                            <a href="{% url 'highschool:teacher-detail' teacher.id %}">{{ teacher.full_name }}</a> (<a href="{% url 'highschool:subject-detail' teacher.subject.id %}">{{ teacher.subject }}</a>)
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="ui icon warning message">
                <i class="exclamation triangle icon"></i>
                <div class="content">
                    <div class="header">
                        Aucune enseignant associé à cette classe
                    </div>
                    <p>Vous devriez commencer par associer des enseignants à cette classe</p>
                </div>
            </div>
        {% endif %}
    </div>

    <div class="sixteen wide column">
        <h3 class="ui header dividing">Liste des étudiant(s)</h3>
    </div>

    <div class="sixteen wide column">
        {% if classroom.students.count > 0 %}
            <div class="ui middle aligned relaxed list">
                {% for student in classroom.students.all %}
                    <div class="item">
                        <i class="angle right icon"></i>
                        <div class="content">
                            <div class="description">
                                <a href="{% url 'highschool:student-detail' student.id %}">{{ student }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="ui icon warning message">
                <i class="exclamation triangle icon"></i>
                <div class="content">
                    <div class="header">
                        Aucun étudiant dans cette classe
                    </div>
                    <p>Vous devriez commencer par ajouter des étudiants à cette classe</p>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

highschool/templates/highschool/classroom/list.html
{% extends 'base.html' %}

{% block title %}Gestion des classes{% endblock %}

{% block page-script %}
    <script type="text/javascript">
        $(document).ready(function () {
           $('table').tablesort();
        });
    </script>
{% endblock %}

{% block content %}

    {# Page title #}
    <div class="sixteen wide column">
        <h2 class="ui icon header d-block">
            <i class="users icon"></i>
            <div class="content">
                Gestion des classes
                <div class="sub header">Visualiser et gérer les classes de l'établissement.</div>
            </div>
        </h2>
    </div>

    {# Actions #}
    <div class="sixteen wide column">
        <a href="{% url 'highschool:classroom-create' %}" class="ui labeled icon button d-block blue">
            <i class="plus icon"></i>
            Créer une classe
        </a>
    </div>

    {# List of all classrooms #}
    {% if classroom_list.count > 0 %}
        <div class="sixteen wide column">
            <table class="ui sortable compact tablet stackable celled striped single line table">
                <thead>
                    <tr>
                        <th style="width: 100%">Nom</th>
                        <th>Formation</th>
                        <th>Année</th>
                        <th>Nb. élève</th>
                    </tr>
                </thead>
                <tbody>
                    {% for classroom in classroom_list %}
                        <tr>
                            <td>
                                <a href="{% url 'highschool:classroom-detail' classroom.id %}">{{ classroom.class_name }}</a>
                            </td>
                            <td>{{ classroom.academic_grade }}</td>
                            <td>{{ classroom.start_at|date:"Y" }} - {{ classroom.end_at|date:"Y" }}</td>
                            <td>{{ classroom.students.count }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include 'highschool/misc/pagination.html' with page_obj=page_obj %}
        </div>
    {% else %}
        <div class="sixteen wide column">
            <div class="ui icon warning message">
                <i class="exclamation triangle icon"></i>
                <div class="content">
                    <div class="header">Aucune classe existante !</div>
                    <p>Commencez par créer des classes.</p>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

highschool/templates/highschool/classroom/update.html
{% extends 'highschool/classroom/form.html' %}

{% block title %}Mettre à jour la classe &laquo; {{ classroom.class_name }} &raquo;{% endblock %}