accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from .views import LoginView

app_name = 'accounts'
urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login')),
    path('login', LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

highschool/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from . import views

app_name = 'highschool'
urlpatterns = [
    # example: /lycee/
    path('', views.index, name='index'),

    # Example (see all): /lycee/students
    path('students', views.StudentListView.as_view(), name='student-list'),
    # Example (see specific): /lycee/student/1
    path('student/<int:pk>', views.StudentDetailView.as_view(), name='student-detail'),
    # Example (create): /lycee/student/create
    path('student/create', views.StudentCreateView.as_view(), name='student-create'),
    # Example (edit): /lycee/student/edit/1
    path('student/update/<pk>', views.StudentUpdateView.as_view(), name='student-update'),
    # Example (delete): /lycee/student/delete/1
    path('student/delete/<pk>', views.StudentDeleteView.as_view(), name='student-delete'),

    #region -> (permissions)

    path('groups', views.GroupListView.as_view(), name='group-list'),
    path('group/<int:pk>', views.GroupDetailView.as_view(), name='group-detail'),
    path('group/create', views.GroupCreateView.as_view(), name='group-create'),
    path('group/update/<int:pk>', views.GroupUpdateView.as_view(), name='group-update'),
    path('group/delete/<int:pk>', views.GroupDeleteView.as_view(), name='group-delete'),

    # endregion

    # region -> (teachers)

    path('teachers', views.TeacherListView.as_view(), name='teacher-list'),
    path('teacher/<int:pk>', views.TeacherDetailView.as_view(), name='teacher-detail'),
    path('teacher/create', views.TeacherCreateView.as_view(), name='teacher-create'),
    path('teacher/update/<int:pk>', views.TeacherUpdateView.as_view(), name='teacher-update'),
    path('teacher/delete/<int:pk>', views.TeacherDeleteView.as_view(), name='teacher-delete'),

    # endregion

    # region -> (academic grades)

    path('academic-grades', views.AcademicGradeListView.as_view(), name='academic-grade-list'),
    path('<int:pk>', views.AcademicGradeDetailView.as_view(), name='academic-grade-detail'),
    path('academic-grade/create', views.AcademicGradeCreateView.as_view(), name='academic-grade-create'),
    path('academic-grade/update/<int:pk>', views.AcademicGradeUpdateView.as_view(), name='academic-grade-update'),
    path('academic-grade/delete/<int:pk>', views.AcademicGradeDeleteView.as_view(), name='academic-grade-delete'),

    # endregion

    # region -> (classroom)

    path('classrooms', views.ClassroomListView.as_view(), name='classroom-list'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/create', views.ClassroomCreateView.as_view(), name='classroom-create'),
    path('classroom/update/<int:pk>', views.ClassroomUpdateView.as_view(), name='classroom-update'),
    path('classroom/delete/<int:pk>', views.ClassroomDeleteView.as_view(), name='classroom-delete'),

    # Classroom calls registers
    # path('classroom/<int:pk>/call_registers', views.ClassroomAttendanceListView.as_view(), name='classroom-call-register-list'),
    # path('classroom/<int:class_id>/call_register/<int:pk>', views.ClassroomAttendanceCreateView.as_view(), name='classroom-call-register-detail'),
    # path('classroom/<int:pk>/call_register/create', views.ClassroomAttendanceCreateView.as_view(), name='classroom_call_the_roll'),
    # path('classroom/<int:class_id>/call_register/update/<int:pk>', views.ClassroomAttendanceCreateView.as_view(), name='classroom-call-register-update'),
    # path('classroom/<int:class_id>/call_register/delete/<int:pk>', views.ClassroomAttendanceCreateView.as_view(), name='classroom-call-register-delete'),

    # Classroom planning
    path('classroom/<int:class_id>/planning', views.ClassroomPlanning.as_view(), name='classroom-planning'),

    # Classroom lessons management
    path('classroom/<int:class_id>/lessons', views.ClassroomLessonListView.as_view(), name='classroom-lesson-list'),
    path('classroom/<int:class_id>/lesson/<int:pk>', views.ClassroomLessonDetailView.as_view(), name='classroom-lesson-detail'),
    path('classroom/<int:class_id>/lesson/create', views.ClassroomLessonCreateView.as_view(), name='classroom-lesson-create'),
    path('classroom/<int:class_id>/lesson/update/<int:pk>', views.ClassroomLessonUpdateView.as_view(), name='classroom-lesson-update'),
    path('classroom/<int:class_id>/lesson/delete/<int:pk>', views.ClassroomLessonDeleteView.as_view(), name='classroom-lesson-delete'),

    # Classroom lesson attendance
    path('classroom/<int:class_id>/lesson/<int:lesson_id>/call_register/create', views.LessonAttendanceCreateView.as_view(), name='classroom-lesson-attendance-create'),
    path('classroom/<int:class_id>/lesson/<int:lesson_id>/call_register/update', views.LessonAttendanceUpdateView.as_view(), name='classroom-lesson-attendance-update'),


    # path('classroom/<int:class_id>/course/create', name='classroom-course-create'),

    # endregion

    # region -> (subject)

    path('subjects', views.SubjectListView.as_view(), name='subject-list'),
    path('subject/<int:pk>', views.SubjectDetailView.as_view(), name='subject-detail'),
    path('subject/create', views.SubjectCreateView.as_view(), name='subject-create'),
    path('subject/update/<int:pk>', views.SubjectUpdateView.as_view(), name='subject-update'),
    path('subject/delete/<int:pk>', views.SubjectDeleteView.as_view(), name='subject-delete'),

    # endregion
]

schoolmanagementapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

handler400 = 'highschool.views.handler400'
handler403 = 'highschool.views.handler403'
handler404 = 'highschool.views.handler404'
# handler500 = 'highschool.views.handler500'


urlpatterns = [
    path('', RedirectView.as_view(url="/lycee/")),
    path('', include('accounts.urls')),
    path('lycee/', include('highschool.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('accounts.urls'))
]

highschool/forms/academic_grade.py
from django import forms

from ..models import AcademicGrade


class AcademicGradeForm(forms.ModelForm):
    class Meta:
        model = AcademicGrade
        fields = ['diploma_short_name', 'diploma_full_name', 'formation_short_name', 'formation_full_name', 'year_after_bac']

highschool/forms/attendance.py
from django import forms

from ..models import Attendance


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = ['student', 'lesson', 'is_absent']

highschool/forms/classroom.py
from django import forms

from ..models import Classroom


class ClassroomForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = ['academic_grade', 'teachers', 'students', 'start_at', 'end_at', 'class_name']

highschool/forms/group.py
from django import forms

from django.contrib.auth import models as auth_models

class GroupForm(forms.ModelForm):
    class Meta:
        model = auth_models.Group
        fields = ['name', 'permissions']

highschool/forms/student.py
from django import forms

from ..models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('phone', 'birth_date', 'genre')
        exclude = ('user',)

highschool/forms/teacher.py
from django import forms

from ..models import Teacher


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['phone', 'birth_date', 'genre', 'subject']
        exclude= ['user']

highschool/views/academic_grade.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from ..models import AcademicGrade
from ..forms import AcademicGradeForm


class AcademicGradeListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    """ Lists all existing academic grades. """
    paginate_by = 25
    ordering = ['-id']
    model = AcademicGrade
    template_name = 'highschool/academic-grade/list.html'

    permission_required = (
        'highschool.view_academicgrade'
    )


class AcademicGradeDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    """ Details a specific academic grade. """
    model = AcademicGrade
    template_name = 'highschool/academic-grade/detail.html'

    permission_required = (
        'highschool.view_academicgrade'
    )


class AcademicGradeCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    """ Creates a new academic grade. """
    form_class = AcademicGradeForm
    success_url = reverse_lazy('highschool:academic-grade-list')
    template_name = 'highschool/academic-grade/create.html'

    permission_required = (
        'highschool.create_academicgrade'
    )

    def get_context_data(self, **kwargs):
        print(self.request.user.get_all_permissions())
        context = super(AcademicGradeCreateView, self).get_context_data(**kwargs)
        context['cs_form_type'] = 'create'
        return context


class AcademicGradeUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    """ Updates a specific academic grade. """
    model = AcademicGrade
    form_class = AcademicGradeForm
    template_name = 'highschool/academic-grade/update.html'

    permission_required = (
        'highschool.change_academicgrade'
    )

    def get_context_data(self, **kwargs):
        context = super(AcademicGradeUpdateView, self).get_context_data(**kwargs)
        context['cs_form_type'] = 'update'
        return context

    def get_success_url(self):
        return reverse_lazy('highschool:academic-grade-detail', args=[self.object.id])


class AcademicGradeDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    """ Deletes a specific academic grade. """
    model = AcademicGrade
    template_name = 'highschool/academic-grade/delete.html'
    success_url = reverse_lazy('highschool:academic-grade-list')

    permission_required = (
        'highschool.delete_academicgrade'
    )

highschool/views/default_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

import datetime

from ..models import AcademicGrade, Student, Teacher, Classroom


@login_required
def index(request):
    context = {
        'statistics': {
            'academic_grades': AcademicGrade.objects.count(),
            'students': Student.objects.count(),
            'teachers': Teacher.objects.count()
        },
        'academics_grades': AcademicGrade.objects.all()
    }
    return render(request, 'highschool/index.html', context)

highschool/views/errors.py
from django.shortcuts import render

def handler400(request, exception):
    return render(request, 'highschool/errors/error_400.html', { 'exception': exception })

def handler403(request, exception):
    return render(request, 'highschool/errors/error_403.html', { 'exception': exception })

def handler404(request, exception):
    return render(request, 'highschool/errors/error_404.html', { 'exception': exception })

def handler500(request, exception):
    return render(request, 'highschool/errors/error_500.html', { 'exception': exception })

highschool/views/group.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin

from ..forms import GroupForm


class GroupListView(LoginRequiredMixin, generic.ListView):
    """ List all existing groups. """
    model = Group
    paginate_by = 25
    ordering = ['-id']
    template_name = 'highschool/group/list.html'


class GroupDetailView(LoginRequiredMixin, generic.DetailView):
    """ Details a specific group. """
    model = Group
    template_name = 'highschool/group/detail.html'

class GroupCreateView(LoginRequiredMixin, generic.CreateView):
    """ Creates a new group. """
    form_class = GroupForm
    template_name = 'highschool/group/create.html'
    success_url = reverse_lazy('highschool:group-list')

    def get_context_data(self, **kwargs):
        context = super(GroupCreateView, self).get_context_data(**kwargs)
        context['cs_form_type'] = 'create'
        return context


class GroupUpdateView(LoginRequiredMixin, generic.UpdateView):
    """ Updates a specific group. """
    model = Group
    form_class = GroupForm
    template_name = 'highschool/group/update.html'

    def get_context_data(self, **kwargs):
        context = super(GroupUpdateView, self).get_context_data(**kwargs)
        context['cs_form_type'] = 'update'
        context['selected'] = {
            'permission_ids': [perm.id for perm in self.object.permissions.all()]
        }
        return context

    def get_success_url(self):
        return reverse_lazy('highschool:group-detail', args=[self.object.id])


class GroupDeleteView(LoginRequiredMixin, generic.DeleteView):
    """ Deletes a specific group. """
    model = Group
    success_url = reverse_lazy('highschool:group-list')
    template_name = 'highschool/group/delete.html'

highschool/views/student.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from ..models import Student
from ..forms import StudentForm, UserCreationForm


class StudentListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    """ List all existing students. """
    template_name = 'highschool/student/list.html'
    model = Student
    paginate_by = 25

    permission_required = (
        'highschool.view_student'
    )

class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    """ Creates a new student. """
    model = Student
    form_class = StudentForm
    template_name = 'highschool/student/create_update.html'

    permission_required = (
        'highschool.create_student'
    )

    def get(self, request, *args, **kwargs):
        print(self.request.user.get_user_permissions())
        print(self.request.user.get_group_permissions())
        print(self.request.user.get_all_permissions())
        return super(StudentCreateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(StudentCreateView, self).get_context_data(**kwargs)
        context['user_form'] = UserCreationForm()
        context['cs_form_type'] = 'create'
        return context

    def form_valid(self, form):
        user_form: UserCreationForm = UserCreationForm(data=self.request.POST)
        if user_form.is_valid() and form.is_valid():
            user: User = user_form.save()
            student: Student = form.save(commit=False)
            student.user_id = user.id
            student.save()
        return HttpResponseRedirect(reverse_lazy('highschool:student-list'))


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    """ Updates a specific student. """
    model = Student
    form_class = StudentForm
    template_name = 'highschool/student/create_update.html'

    permission_required = (
        'highschool.change_student'
    )

    def get_context_data(self, **kwargs):
        context = super(StudentUpdateView, self).get_context_data(**kwargs)
        context['user_form'] = UserChangeForm(self.request.POST or None, instance=self.object.user)
        context['cs_form_type'] = 'update'
        context['selected'] = {
            'genre': self.object.genre,
            'group_ids': [group.id for group in self.object.user.groups.all()],
            'permission_ids': [permission.id for permission in self.object.user.user_permissions.all()],
        }
        return context

    def form_valid(self, form):
        user_form: UserChangeForm = UserChangeForm(self.request.POST, instance=self.object.user)
        if user_form.is_valid():
            user: User = user_form.save()
            if form.is_valid():
                student: Student = form.save(commit=False)
                student.user_id = user.id
                student.save()
            else:
                return self.form_invalid(form)
        else:
            return self.form_invalid(user_form)
        return HttpResponseRedirect(reverse_lazy('highschool:student-detail', args=[self.object.id]))

    def get_success_url(self):
        return reverse_lazy('highschool:student-detail', args=[self.object.id])


class StudentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Student
    template_name = 'highschool/student/delete.html'
    success_url = reverse_lazy('highschool:student-list')

    permission_required = (
        'highschool.delete_student'
    )

class StudentDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    template_name = 'highschool/student/detail.html'
    model = Student

    permission_required = (
        'highschool.view_student'
    )

highschool/templates/highschool/classroom/lesson/delete.html
{% extends "base.html" %}

{% block title %}Suppression de la leçon &laquo; {{ lesson.page_title|safe }} &raquo;{% endblock %}

{% block content %}

    {# Page title #}
    <div class="sixteen wide column">
        <h2 class="ui icon header d-block">
            <i class="calendar outline alternate icon"></i>
            <div class="content">
                Suppression de la leçon &laquo; {{ lesson.page_title|safe }} &raquo;
                <div class="sub header">Supprimer définitivement une leçon d'un classe spécifique.</div>
            </div>
        </h2>
    </div>

    {# Warning #}
    <div class="sixteen wide column">
        <div class="ui icon warning message">
            <i class="exclamation triangle icon"></i>
            <div class="content">
                <div class="header">
                    Vous allez supprimer une leçon, la suppression de cette leçon implique :
                </div>
                <div class="ui list">
                    <div class="item">
                        <i class="check green icon"></i>
                        <div class="content">
                            La suppression <b>définitive et irréversible</b> de cette leçon
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {# Form #}
    <div class="sixteen wide column">
        <form method="post" class="ui form">
            {% csrf_token %}
            <div class="ui buttons w-100">
                <a href="{% url 'highschool:classroom-lesson-detail' class_id=classroom.id pk=lesson.id %}" class="ui button">Annuler</a>
                <div class="or" data-text="ou"></div>
                <input type="submit" value="Supprimer" class="ui negative button">
            </div>
        </form>
    </div>
{% endblock %}

highschool/templates/highschool/classroom/lesson/detail.html
{% extends 'base.html' %}

{% block title %}{{ lesson.page_title|safe }}{% endblock %}

{% block content %}

    {# Page title #}
    <div class="sixteen wide column">
        <h2 class="ui icon header d-block">
            <i class="calendar outline alternate icon"></i>
            <div class="content">
                {{ lesson.page_title|safe }}
                <div class="sub header">Visualiser et gérer une leçon spécifique.</div>
            </div>
        </h2>
    </div>

    <div class="sixteen wide column">
        <h3 class="ui header dividing">Informations</h3>
    </div>

    {# Actions #}
    <div class="eight wide computer sixteen wide mobile column">
        <a href="{% url 'highschool:classroom-lesson-update' class_id=classroom.id pk=lesson.id %}" class="ui labeled icon button d-block">
            <i class="edit icon"></i>
            Mettre à jour
        </a>
    </div>
    <div class="eight wide computer sixteen wide mobile column">
        <a href="{% url 'highschool:classroom-lesson-delete' class_id=classroom.id pk=lesson.id %}" class="ui labeled icon negative button d-block">
            <i class="trash icon"></i>
            Supprimer
        </a>
    </div>

    {# Lesson informations #}
    <div class="sixteen wide column">
        <div class="ui middle aligned relaxed list">
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Matière : </b> <a href="{% url 'highschool:subject-detail' lesson.subject.id %}">{{ lesson.subject }}</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Enseignant référant : </b> <a href="{% url 'highschool:teacher-detail' lesson.teacher.id %}">{{ lesson.teacher.full_name }}</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Date de début : </b> {{ lesson.start_at|date:'d F Y à H:i' }}
                    </div>
                </div>
            </div>
            <div class="item">
                <i class="angle right icon"></i>
                <div class="content">
                    <div class="description">
                        <b>Date de fin : </b> {{ lesson.end_at|date:'d F Y à H:i' }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="sixteen wide column">
        <h3 class="ui header dividing">Appel de la classe</h3>
    </div>

    {# Actions #}
    <div class="sixteen wide column">
        {% if lesson.has_attendance %}
            <a href="{% url 'highschool:classroom-lesson-attendance-update' class_id=classroom.id lesson_id=lesson.id %}" class="ui labeled blue icon button d-block">
                <i class="bullhorn icon"></i>
                Modifier l'appel
            </a>

        {% else %}
            <a href="{% url 'highschool:classroom-lesson-attendance-create' class_id=classroom.id lesson_id=lesson.id %}" class="ui labeled blue icon button d-block">
                <i class="bullhorn icon"></i>
                Faire l'appel
            </a>
        {% endif %}
    </div>

    {# Lesson attendance informations #}
    {% if lesson.has_attendance %}
        <div class="sixteen wide column">
            <div class="ui middle aligned relaxed list">
                    <div class="item">
                        <i class="angle right icon"></i>
                        <div class="content">
                            <div class="description">
                                <b>Liste étudiants absents : </b>
                                {% if lesson.absent_students|length == 0 %}Aucun{% endif %}
                            </div>
                            <div class="list">
                                {% for student in lesson.absent_students %}
                                    <div class="item">
                                        <i class="angle right icon"></i>
                                        <div class="content">
                                            <div class="description"><a href="{% url 'highschool:student-detail' student.id %}">{{ student }}</a></div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    {% endif %}

{% endblock %}

highschool/templates/highschool/classroom/lesson/list.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block page-script %}{% endblock %}
{% block page-style %}{% endblock %}

{% block content %}

    {# Page title #}
    <div class="sixteen wide column">
        <h2 class="ui icon header d-block">
            <i class="calendar alternate outline icon"></i>
            <div class="content">
                Gestion des cours de la classe &laquo; {{ classroom }} &raquo;
                <div class="sub header">Visualiser et gérer les cours d'une classe spécifique.</div>
            </div>
        </h2>
    </div>

    {# Actions #}
    <div class="sixteen wide column">
        <a href="{% url 'highschool:classroom-lesson-create' class_id=classroom.id %}" class="ui labeled icon button d-block blue">
            <i class="plus icon"></i>
            Créer un cours
        </a>
    </div>

    {# List of all courses #}
    {% if object_list.count > 0 %}
        <div class="sixteen wide column">
            <table class="ui sortable compact tablet stackable celled striped single line table">
                <thead>
                    <tr>
                        <th>Enseignant (Matière)</th>
                        <th style="width: 100%">Liste des leçons</th>
                    </tr>
                </thead>
                <tbody>
                    {% regroup object_list by classroom_teacher as lessons_by_class_teacher %}
                    {% for subject_group in lessons_by_class_teacher %}
                        <tr>
                            <td style="display: flex; flex-direction: column; align-items: center">
                                <a href="{% url 'highschool:teacher-detail' subject_group.grouper.teacher.id %}">{{ subject_group.grouper.teacher_name }}</a>
                                <span>(<a href="{% url 'highschool:subject-detail' subject_group.grouper.teacher.subject.id %}">{{ subject_group.grouper.subject_name }}</a>)</span>
                            </td>
                            <td>
                                <div class="ui styled fluid accordion">
                                    <div class="title">
                                        <i class="dropdown icon"></i>
                                        {{ subject_group.list|length }} leçon(s) programmée(s)
                                    </div>
                                    <div class="content">
                                        <div class="ui list">
                                            {% for lesson in subject_group.list %}
                                                <div class="item" style="white-space: initial">
                                                    <i class="check icon green"></i>
                                                    <div class="content">
                                                        <a href="{% url 'highschool:classroom-lesson-detail' class_id=classroom.id pk=lesson.id %}">{{ lesson.simple }}</a>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include 'highschool/misc/pagination.html' with page_obj=page_obj %}
        </div>
    {% else %}
        <div class="sixteen wide column">
            <div class="ui icon warning message">
                <i class="exclamation triangle icon"></i>
                <div class="content">
                    <div class="header">Aucun cours existant !</div>
                    <p>Commencez par créer des cours .</p>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}